### ISSUE TITLE
Transfer not changing `updateAuthority` field

### ISSUE THREAD

**Issue by jim4067** [metaplex-foundation/mpl-core#110]
When transferring an asset to a new account using the transfer delegate plugin, I expect it update all the authoritative fields to a new owner. 

Instead, the `updateAuthority` still the previous owner's address. 

e.g this asset address `HFe8FwVKEv6Y77qddG4AHirTbereurM39QhEsB5qrxxG` 

```js
{
  publicKey: 'HFe8FwVKEv6Y77qddG4AHirTbereurM39QhEsB5qrxxG',
  header: {
    executable: false,
    owner: 'CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d',
    lamports: { basisPoints: 4325760n, identifier: 'SOL', decimals: 9 },
    rentEpoch: 18446744073709552000,
    exists: true
  },
  pluginHeader: { key: 3, pluginRegistryOffset: 185n },
  transferDelegate: { authority: { type: 'Owner', address: undefined }, offset: 182n },
  freezeDelegate: {
    authority: { type: 'Owner', address: undefined },
    offset: 183n,
    frozen: false
  },
  key: 1,
  owner: 'J63YroB8AwjDVjKuxjcYFKypVM3aBeQrfrVmNBxfmThB',
  updateAuthority: {
    type: 'Address',
    address: '4kg8oh3jdNtn7j2wcS7TrUua31AgbLzDVkBZgTAe44aF'
  },
  name: 'Kobeni Supremacy',
  uri: 'https://raw.githubusercontent.com/687c/solana-nft-native-client/main/metadata.json',
  seq: { __option: 'None' }
}
```

**Comment by blockiosaurus** [comment]
Hey @jim4067. The update authority is a separate field. It's intended to be an authority over the metadata itself and isn't indicative of possession. To change this you will need to call Update.

**Comment by jim4067** [comment]
Thanks for the clarification @blockiosaurus.

Correct me if I'm wrong, but I assume that trying to update the metadata after transfer to the new address would fail because this field contains my old address right?

**Comment by blockiosaurus** [comment]
Correct. The update authority sticks with the same Pubkey, usually the creator. For example, if a creator minted a collection of NFTs but made a typo, they'd want to be able to fix those even though the owner has changed.

**Comment by jim4067** [comment]
Thanks for the clarification. That makes sense
