### ISSUE TITLE
Question : Reason behind not using Solana-program v1.18

### ISSUE THREAD

**Issue by nabeel99** [metaplex-foundation/mpl-core#139]
### Problem
I was curious behind the reason of gating the solana-program to ">v1.14 < v1.18",  since this wont compile in any program using anchor spl v0.30.0, as it has a dependency on spl-associated-token-account v3, which requires a minimum version of v1.18.2.

anchor spl cargo.toml -> https://github.com/coral-xyz/anchor/blob/master/spl/Cargo.toml
spl-associatd token account -> https://github.com/solana-labs/solana-program-library/blob/78da1843fc515e4aa9e18ea48b71d2b903e5e6ea/associated-token-account/program/Cargo.toml#L19

**Comment by danenbm** [comment]
Should work now with https://crates.io/crates/mpl-core/0.7.1

**Comment by danenbm** [comment]
Original reason was lack of semver with Solana releases often caused issues in the past
