### ISSUE TITLE
mpl-core rust docs broken link

### ISSUE THREAD

**Issue by mael-bomane** [metaplex-foundation/mpl-core#147]
on the webpage `https://developers.metaplex.com/core/getting-started/rust` 

the link in this sentence redirects to 404 `For a more comprehensive guide on Builder instruction types please visit the [Working with Rust](https://developers.metaplex.com/core/getting-started/working-with-rust#working-with-rust-scripts-locally) page.`

**Comment by MarkSackerberg** [comment]
This has been fixed. Thank you @mael-bomane !
