### ISSUE TITLE
More balance is left in burnt asset account than docs claim (0.00239784 vs 0.00089784)

### ISSUE THREAD

**Issue by zpalmtree** [metaplex-foundation/mpl-core#183]
Hello,

I have been testing burning with MPL Core assets. The documentation mentions that 0.00089784 sol should be left in an account after a burn.

https://developers.metaplex.com/core/burn

But, from my testing, this number seems to be 0.00239784 in practice. A few different transactions for reference:

https://solscan.io/tx/58ouytuhovttsjPXWCEGY7B5GcDELL57H5j6tb5QcrroaP73UqT7gyqDjptJVRjYVqwFvG2XsHJjohkvdua7hg6j#solBalanceChange

![image](https://github.com/user-attachments/assets/86d3c45d-65b9-475c-a665-494796be728a)

https://solscan.io/tx/Xp9r7LZ9Erym1ERSSUaJS29awXy953GKiDaiSiBfV3FVCVg4zi11Nyzp3ym3Kwhsbg2A5MCVSxDUHZoZ3Dxgcod#solBalanceChange

![image](https://github.com/user-attachments/assets/9f544c22-bbfa-4ae0-8eae-0951eec06e02)

Are the docs outdated here, or is there a bug causing more sol to be retained than needed?

**Comment by blockiosaurus** [comment]
Hey @zpalmtree,

The protocol fee for minting core assets (0.0015 SOL) is stored in the asset account at mint time. If it's not collected by the fee harvester by the time the asset is burned, it will stay in the account until the harvester reaches it.

The balance you're seeing is the fee + minimum rent. Once the fee is collected all that will remain is the minimum rent, the 0.00089784 SOL specified in the docs.

**Comment by zpalmtree** [comment]
> Hey @zpalmtree,
> 
> The protocol fee for minting core assets (0.0015 SOL) is stored in the asset account at mint time. If it's not collected by the fee harvester by the time the asset is burned, it will stay in the account until the harvester reaches it.
> 
> The balance you're seeing is the fee + minimum rent. Once the fee is collected all that will remain is the minimum rent, the 0.00089784 SOL specified in the docs.

Understood. Is there any way to detect if this fee has been harvested or not, so we can determine how many lamports we will reclaim from the burn?

**Comment by blockiosaurus** [comment]
To fetch the amount of rent that will be returned, you just need to run
`connection.getMinimumBalanceForRentExemption(<CoreAccountDataLength>) - 0.00089784 SOL`
It's simply the amount required for rent exemption, minus the amount required to keep the account open.
