### ISSUE TITLE
v0.4.0 release empty

### ISSUE THREAD

**Issue by joefitter** [metaplex-foundation/mpl-core#38]
When installing core v0.4.0 the dep is empty. (Installs with just package.json and readme)

0.3.0 installs as expected.

Both of these versions have to be force installed if using NPM and already using mpl-toolbox as Core has a dependency on 0.8.0 (I have 0.9.4 in my app)

**Comment by blockiosaurus** [comment]
Thanks! I hate NPM. There was an additional issue with 4.0 so we published 4.2 as a reversion to 3.0.
