### ISSUE TITLE
Missing assets from collection

### ISSUE THREAD

**Issue by joefitter** [metaplex-foundation/mpl-core#45]
I am building a suite of tools including a conversion app and Core marketplace, and I noticed a recently minted Core collection has 2 minted and 2 current assets, but these cannot be found with any of the GPA builder or helper fetch methods.

I had assumed that if the child assets were burned then the `currentSize` would reflect this?

The collection address is C5LGCSmm9QYUFs9NfwryAmWsg4bvawT4dY9LKRx8Pikh

**Comment by joefitter** [comment]
Another Core collection has been created with the same issue - GWhZEfsKp4cZjFKxchbbSqU96MnRpZGAJ1RQShMCVM4n

5 current assets, but none found when searching by the collection.

**Comment by joefitter** [comment]
OK looking through the tx logs 5 core assets were minted into the above collection, an example of one is 7XsUFpgCuhzfMu8Rp3hBPYHofAM9s6UCG92EGye66yi4 - looking at the program logs, there is an update operation after the mint, which updates the update_authority of the core asset to the owner, and breaks the collection link.

This should not be possible, as the collection is left with 5 current assets, but by updating the update_authority the asset is no longer part of the collection

**Comment by danenbm** [comment]
Fixed by you!  Thank you again for finding and fixing this issue.
https://github.com/metaplex-foundation/mpl-core/pull/54
