### ISSUE TITLE
Unexpected asset plugin behaviour

### ISSUE THREAD

**Issue by joefitter** [metaplex-foundation/mpl-core#49]
There is some strange behaviour when interacting with assets that have a permanent authority. For example:

1) Create collection with permanent transfer authority
2) Create asset in this collection
3) Delegate transfer authority and freeze authority to a third party program, freeze the asset.
4) The transfer authority can still transfer the asset regardless
5) After the transfer, the asset still has `frozen: true`, but the authority is updated to `Owner`
6) The transfer authority on the asset is also set to `Owner`

To me, frozen is frozen, and nothing should be able to move the asset. I would suggest an alternative solution for this case would be to disable the owner adding freeze/transfer authority if there is a permanent authority in place.

**Comment by blockiosaurus** [comment]
While we call this frozen, the semantics are slightly different than the tradition spl-token freeze semantics. This was an intentional choice to use frozen as an indicator of blocked lifecycle events, not as a freeze state.
