### ISSUE TITLE
Question: how to retrieve attribute list from a particular asset?

### ISSUE THREAD

**Issue by pernifin** [metaplex-foundation/mpl-core#57]
So basically title ☝🏻

Documentation https://developers.metaplex.com/core/plugins/attribute describes how to add or update attributes on a particular asset. But there is no way to retrieve stored attributes via JS api. 

I know about your DAS API but I'm not going to launch full RPC node just to get simple value out of a particular asset by its address. Is there any simple way?

**Comment by blockiosaurus** [comment]
`fetchAssetV1` fetches the Asset and all of its associated plugins and represents them as properties on the asset object. So if you Asset has the attribute object it should have a property like the following.
```
attributes: {
      authority: {
        type: 'UpdateAuthority',
      },
      attributeList: [
        { key: 'key0', value: 'value0' },
        { key: 'key1', value: 'value1' },
      ],
    },
```

**Comment by pernifin** [comment]
Cool. It works, thank you!
